### ISSUE TITLE
IndexError: list index out of range at Step 3

### ISSUE THREAD

**Issue by booknary** [ChenRen-SCBG/HomeoSorter#2]
Hi Chen,
Something went wrong at STEP 3 which i can't figure out why, it printed
 "Traceback (most recent call last):
  File "./homeosorter1.py", line 1113, in <module>
    main()
  File "./homeosorter1.py", line 1109, in main
    homeosorter(args)
  File "./homeosorter1.py", line 857, in homeosorter
    glob.glob(f"{running_output_dir}/3_astral/*_{start_tree_string}-{end_tree_string}*Best*taxonmap")[0],
IndexError: list index out of range"
And there is no taxonmap file in 3_astral, could you please check my files? Thanks!
The file size is out of limit to upload here, so I upload it to google drive: https://drive.google.com/file/d/1VMWot6NJ4pWZrAqnx3gSlQkSacu8WGYv/view?usp=sharing
Homeosorter : 1.1.2
ete3 : 3.1.3
astral : 5.7.8
astral-pro : 1.1.2

**Comment by ChenRen-SCBG** [comment]
Hi booknary,
The issue stems from a constraint I implemented in the script. I limited the number of polyploid samples to seven for HomeoSorter to prevent generating too many subgenome combinations during the second round of ASTRAL analyses. However, it would be more flexible to let users decide on this limit. I’ve addressed this in the latest version (v.1.1.3). Nevertheless, it seems you are attempting to analyze 93 tetraploid samples simultaneously. This would result in a formidable number of subgenome combinations in the second round of ASTRAL analyses, making the computation very inefficient. I would recommend selecting representative tetraploid samples instead of including all of them in the analyses. Alternatively, you can set the parameter “-b” to “1” to skip the second round of ASTRAL analyses.

Additionally, there is an issue with your dataset. HomeoSorter requires that a sample name cannot be part of any other sample names. In your dataset, the sample name “D123” is part of the names of two other samples of “D123A” and “D1231,” which will cause errors in the analyses. You can resolve this by renaming “D123.” I have uploaded an edited tree file where “D123” is renamed to “D123B,” in case you need it. 
[new_tree_file.txt](https://github.com/user-attachments/files/17434723/new_tree_file.txt)

**Comment by booknary** [comment]
Hi Chen,
Yeah I noticed the rule of naming, I just forgot it. Thank you very much for your help!
